---
  language: node_js
  node_js:
    - 12.16.1
  cache:
    yarn: true
    directories:
    - node_modules
  
  env:
    global:
      - PATH=$HOME/.yarn/bin:$PATH
  
  services:
    - mongodb
  
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  
  script:
   - yarn install && yarn lint && yarn test:e2e && yarn test